#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# mariadb-configure
# Configures db using /etc/mariadbconfigure.d
# ==============================================================================

# Reconfigure to be oneshot
s6-svc -O /run/service/mariadb-configure

echo "Waiting for MariaDB to start" | info
# Wait for db to be up before configuring
s6-svwait -U /run/service/mariadb

for f in /etc/mariadbconfigure.d/*.sh; do
  bash "$f"
done

echo "Upgrading db if necessary" | info
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive | info

echo "Refreshing db" | info
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive -f | info

# Notify s6 service is up
fdmove 1 3 printf "done\n"
