#!/command/with-contenv bash
# ==============================================================================
# Mariadb
# Take down the S6 supervision tree if db is no longer accessible
# ==============================================================================

/run/s6/basedir/bin/halt
