#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# Nginx
# Runs Nginx
# ==============================================================================

echo "Waiting for ZoneMinder to start" | info
/bin/s6-svwait -U /var/run/s6/services/zoneminder

echo "Starting Nginx..." | info

exec fdmove -c 2 1 nginx -g 'daemon off;'
