#!/usr/bin/with-contenv bash
# ==============================================================================
# Mariadb
# Take down the S6 supervision tree if db is no longer accessible
# ==============================================================================

redirfd -w 2 /dev/null s6-svscanctl -t /var/run/s6/services
