#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# Mariadb
# Stub service to monitor db status
# ==============================================================================

s6-notifyoncheck -n 1000 echo "Waiting for Mariadb to start" | info

# Wait until db is initially ready before polling
/bin/s6-svwait -U /var/run/s6/services/mariadb
echo "Mariadb is up! Proceeding to monitoring." | info

# Need to sleep to act like service is running
# Terminate container if db dies
until ! (mysqladmin ping --connect-timeout 5 -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" 2>&1 |
  grep 'mysqld is alive' > /dev/null); do
  sleep 1
done
echo "Mariadb could not be reached! Exiting..." | error
echo -n "1" > /var/run/s6/container_environment/SHUTDOWN_REASON_DB_IS_DOWN
