#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
program_name="Mariadb"
# ==============================================================================
# Mariadb
# Stub service to monitor db status
# ==============================================================================

s6-notifyoncheck -n 1000 echo "Waiting for Mariadb to start" | info "${program_name}"

# Wait until db is initially ready before polling
/bin/s6-svwait -U /var/run/s6/services/mariadb
echo "Mariadb is up! Proceeding to monitoring." | info "${program_name}"

# Need to sleep to act like service is running
# Terminate container if db dies
until ! (mysqladmin ping --connect-timeout 5 -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -hdb 2>&1 |
  grep 'mysqld is alive' > /dev/null); do
  sleep 1
done
echo "Mariadb could not be reached! Exiting..." | error "${program_name}"
