#!/usr/bin/with-contenv bash
# ==============================================================================
# ZoneMinder
# Take down the S6 supervision tree if db is no longer accessible
# ==============================================================================

s6-setuidgid www-data /usr/bin/zmpkg.pl stop
s6-svscanctl -t /var/run/s6/services
