#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# ZoneMinder
# Runs ZoneMinder
# ==============================================================================

/bin/s6-svwait -u /var/run/s6/services/nginx
/bin/s6-svwait -u /var/run/s6/services/php-fpm
/bin/s6-svwait -u /var/run/s6/services/fcgiwrap

/bin/s6-svwait -U /var/run/s6/services/mariadb
/bin/s6-svwait -U /var/run/s6/services/mariadb-configure

echo "Starting ZoneMinder..." | info
s6-notifyoncheck -n 1000 s6-setuidgid www-data /usr/bin/zmpkg.pl start

# Wait until service is alive before polling
/bin/s6-svwait -U /var/run/s6/services/zoneminder
echo "ZoneMinder is up! Proceeding to monitoring." | info

# Need to sleep to act like service is running
# Terminate container if zm dies
until [ "$(pgrep -fc /usr/bin/zm)" -lt "1" ]; do
  sleep 1
done
echo "ZoneMinder has crashed! Exiting..." | error
# This is required or the container stop hangs
s6-svscanctl -t /var/run/s6/services
