#!/usr/bin/with-contenv bash
# ==============================================================================
# ZoneMinder
# Runs ZoneMinder
# ==============================================================================

/bin/s6-svwait -u /var/run/s6/services/apache2
/bin/s6-svwait -U /var/run/s6/services/mariadb

echo "Starting ZoneMinder..."
s6-setuidgid abc /usr/bin/zmpkg.pl start

exec \
	s6-setuidgid abc tail -F -q --pid="$(cat /var/run/zoneminder/zm.pid)" \
	"$(find /var/log/apache2/error.log -printf '%C@ %p\n' |sort | head -n 2)"
