#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# ZoneMinder
# Runs ZoneMinder
# ==============================================================================

echo "Waiting for Socklog to start" | info
s6-svwait -U /run/service/socklog
echo "Waiting for MariaDB to start" | info
s6-svwait -U /run/service/mariadb
echo "Waiting for mariadb-configure to complete..." | info
s6-svwait -U /run/service/mariadb-configure

echo "Starting ZoneMinder..." | info
s6-setuidgid www-data /usr/bin/zmpkg.pl start

# zmpkg.pl is blocking so no need to wait
echo "ZoneMinder is up! Proceeding to monitoring." | info
# Notify s6 service is up
fdmove 1 3 printf "done\n"

# Need to sleep to act like service is running
# Terminate container if zm dies
until [ "$(pgrep -fc /usr/bin/zm)" -lt "1" ]; do
  sleep 1
done
echo "ZoneMinder has crashed! Exiting..." | error
