#!/usr/bin/with-contenv bash
# ==============================================================================
# Apache2
# Tell Apache2 to stop when container stops
# ==============================================================================

exec /usr/sbin/apache2 -k stop
