#!/usr/bin/with-contenv bash
# ==============================================================================
# Apache2
# Runs Apache2
# ==============================================================================

echo "Starting Apache2..."

source /etc/apache2/envvars
/usr/sbin/apache2ctl -D FOREGROUND
