#!/usr/bin/with-contenv bash
# ==============================================================================
# Apache2
# Runs Apache2
# ==============================================================================

/bin/s6-svwait -u /var/run/s6/services/zoneminder

echo "Starting Apache2..."
source /etc/apache2/envvars
exec \
  s6-setuidgid abc /usr/sbin/apache2 -k start
