#!/usr/bin/with-contenv bash

function zm_db_exists() {
    mysqlshow -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb zm config > /dev/null 2>&1
    RETVAL=$?
    if [ "$RETVAL" = "0" ]; then
        return # ZoneMinder database exists
    fi
    false # ZoneMinder database does not exist
}

mysqladmin ping --connect-timeout 5 -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb > /dev/null 2>&1
result="$?"
if [ "$result" -eq "0" ]; then
    echo "Mariadb has started. Proceeding..."
    if ! zm_db_exists; then
        echo "Creating ZoneMinder db for first run"
        mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb < /usr/share/zoneminder/db/zm_create.sql
    fi
    exit # mysql is running
else
    exit 1 # mysql is not running
fi
