#!/usr/bin/with-contenv bash

if mysqladmin ping --connect-timeout 5 -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -hdb |
  grep 'mysqld is alive' > /dev/null 2>&1; then
    echo "[Mariadb] Mariadb has started. Proceeding..."
    exit # mysql is running
fi
exit 1 # mysql is not running
