#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# Socklog
# Starts socklog to capture logs
# ==============================================================================

s6-socklog -d3 -t3000
