#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# PHP-fpm
# Runs PHP-fpm
# ==============================================================================

echo "Starting PHP-fpm..." | info

exec fdmove 2 1 \
  /usr/sbin/php-fpm"${PHP_VERSION}" --nodaemonize --fpm-config /etc/php/"${PHP_VERSION}"/fpm/php-fpm.conf
