#!/usr/bin/with-contenv bash
# ==============================================================================
# Mariadb
# Stub service to monitor db status
# ==============================================================================

# Reconfigure to be oneshot
/bin/s6-svc -o /var/run/s6/services/mariadb-configure

# Wait for db to be up before configuring
/bin/s6-svwait -U /var/run/s6/services/mariadb

if ! (mysqlshow -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb zm config > /dev/null 2>&1); then
    echo "[Mariadb-configure] Creating ZoneMinder db for first run"
    mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb < /usr/share/zoneminder/db/zm_create.sql
fi

if [ "$(mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb zm -e \
  "SELECT COUNT(*) FROM Servers WHERE Name = '${ZM_SERVER_HOST}';"  |
  cut -d \t -f 2 |
  sed -n '2 p')" \
  == "0" ]; then
    echo "[Mariadb-configure] Adding MultiServer db entry"
    insert_command="LOCK TABLES \`Servers\` WRITE;"
    insert_command+="INSERT INTO \`Servers\` "
    insert_command+="(Protocol, Hostname, Port, PathToIndex, PathToZMS, PathToApi, Name, zmstats, zmaudit, zmtrigger, zmeventnotification)";
    insert_command+=" VALUES "
    insert_command+="('http','${ZM_SERVER_HOST}',80,'/index.php','/cgi-bin/nph-zms','/zm/api','${ZM_SERVER_HOST}',1,1,1,0);";
    insert_command+="UNLOCK TABLES;"
    mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -hdb zm -e "${insert_command}"
fi

echo "[Mariadb-configure] Upgrading db if necessary"
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive | sed -u "s/^/[Mariadb-configure] /"

echo "[Mariadb-configure] Refreshing db"
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive -f | sed -u "s/^/[Mariadb-configure] /"

# Notify s6 service is up
fdmove 1 3 printf "done\n"
