#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# Mariadb
# Stub service to monitor db status
# ==============================================================================

# Reconfigure to be oneshot
/bin/s6-svc -O /var/run/s6/services/mariadb-configure

# Wait for db to be up before configuring
/bin/s6-svwait -U /var/run/s6/services/mariadb

# if ! (mysqlshow -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" zm config > /dev/null 2>&1); then
if [ "${ZM_FIRST_RUN-0}" -eq "1" ]; then
    echo "Creating ZoneMinder db for first run" | init
    mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" < /usr/share/zoneminder/db/zm_create.sql

    echo "Disabling file log to prevent duplicate logs from syslog" | init
    mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" zm -e "UPDATE Config SET Value = -5 WHERE Name = 'ZM_LOG_LEVEL_FILE';"
fi

if [[ -n "${ZM_SERVER_HOST}" ]] &&
  [ "$(mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" zm -e \
  "SELECT COUNT(*) FROM Servers WHERE Name = '${ZM_SERVER_HOST}';"  |
  cut -f 2 |
  sed -n '2 p')" \
  == "0" ]; then
    echo "Adding multi-server db entry" | init
    insert_command="LOCK TABLES \`Servers\` WRITE;"
    insert_command+="INSERT INTO \`Servers\` "
    insert_command+="(Protocol, Hostname, Port, PathToIndex, PathToZMS, PathToApi, Name, zmstats, zmaudit, zmtrigger, zmeventnotification)";
    insert_command+=" VALUES "
    insert_command+="('http','${ZM_SERVER_HOST}',80,'/index.php','/cgi-bin/nph-zms','/zm/api','${ZM_SERVER_HOST}',1,1,1,0);";
    insert_command+="UNLOCK TABLES;"
    mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" zm -e "${insert_command}"
fi

echo "Upgrading db if necessary" | info
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive | info

echo "Refreshing db" | info
s6-setuidgid www-data /usr/bin/zmupdate.pl -nointeractive -f | info

# Notify s6 service is up
fdmove 1 3 printf "done\n"
