#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
program_name="fcgiwrap"
# ==============================================================================
# fcgiwrap
# Terminate fcgiwrap
# ==============================================================================

echo "Stopping fcgiwrap" | info "${program_name} "
killall -15 fcgiwrap
