#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
program_name="fcgiwrap"
# ==============================================================================
# fcgiwrap
# Runs fcgiwrap
# ==============================================================================

echo "Starting fcgiwrap..." | info "${program_name}"

# Remove old socket if existing
rm /zoneminder/run/fcgiwrap.socket

exec s6-setuidgid www-data fcgiwrap -s unix:/zoneminder/run/fcgiwrap.socket | sed -u "s/^/[${program_name}] /"
