#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# fcgiwrap
# Runs fcgiwrap
# ==============================================================================

echo "Starting fcgiwrap..." | info

# Remove old socket if existing
rm /zoneminder/run/fcgiwrap.socket > /dev/null 2>&1

exec s6-setuidgid www-data fcgiwrap -s unix:/zoneminder/run/fcgiwrap.socket
