#!/usr/bin/with-contenv bash

for _ in {1..3}; do
  if ! (fdmove -c 2 1 \
      mysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" -e 'USE zm;' \
      > /dev/null); then
        exit 1 # mysql is not running
  fi
  sleep 1
done

exit # mysql is running
