#!/usr/bin/with-contenv bash
# ==============================================================================
# MySQL
# Runs MariaDB (drop-in replacement for MySQL)
# ==============================================================================

echo "Starting ZoneMinder..."
exec /usr/bin/zmpkg.pl start
