#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
program_name="Nginx"
# ==============================================================================
# Nginx
# Stops Nginx during container stop to allow shutdown to proceed
# ==============================================================================

echo "Stopping Nginx" | info "${program_name}"
exec nginx -s quit
