#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# Nginx
# Runs Nginx
# ==============================================================================

echo "Starting Nginx..." | info

exec nginx -g 'daemon off;'
