#!/usr/bin/with-contenv bash
. "/usr/local/bin/logger"
program_name="Nginx"
# ==============================================================================
# Nginx
# Runs Nginx
# ==============================================================================

echo "Starting Nginx..." | info "${program_name}"

exec nginx -g 'daemon off;' | sed -u "s/^/[${program_name}] /"
